# Tutorial 3: Algebra lineal usando NumPy - Operaciones básicas con Vectores
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/oscar-ramos/fundamentos-robotica-python/blob/main/0-Introduccion/3-Algebra-Lineal-Vectores.ipynb)

Oscar E. Ramos Ponce, Universidad de Ingeniería y Tecnología - UTEC

* Este archivo muestra el uso básico de vectores con NumPy
* Las operaciones descritas se basan en el capítulo 1 (Vectores) de [este](http://oramosp.epizy.com/teaching/notes/0_algebra_lineal.pdf) documento. La numeración se basa, igualmente, en dicho documento.

In [1]:
import numpy as np

# 1. Vectores

In [2]:
# Vector unidimensional (tamaño n)
v1 = np.array([2, 4, 6])

print("Vector:", v1)
print("Tamaño del vector:", v1.shape)

Vector: [2 4 6]
Tamaño del vector: (3,)


In [3]:
# Vector unidimensional escrito con 2 dimensiones (tamaño nx1)
v2 = np.array([[2], [4], [6]])     # Es igual que: np.array([[2, 4, 6]]).T 

print("Vector:\n", v2)
print("Tamaño del vector:", v2.shape)

Vector:
 [[2]
 [4]
 [6]]
Tamaño del vector: (3, 1)


In [4]:
# Conversión de vector de 1 dimensión a vector de 2 dimensiones
x1 = np.array([2, 4, 6])
x2 = x1[:,None]

print("Tamaño del vector x1:", x1.shape)
print("Tamaño del vector x2:", x2.shape)

Tamaño del vector x1: (3,)
Tamaño del vector x2: (3, 1)


In [5]:
# Conversión de vector de 2 dimensiones a vector de 1 dimensión
x2 = np.array([[2, 4, 6]]).T
x1 = x2.flatten()

print("Tamaño del vector x1:", x2.shape)
print("Tamaño del vector x2:", x1.shape)

Tamaño del vector x1: (3, 1)
Tamaño del vector x2: (3,)


### Transpuesta

In [6]:
# La transpuesta solo tiene sentido cuando se usa 2 dimensiones
print("Usando un vector de 1 sola dimensión:")
print("   v: {}          tamaño de v: {}".format(v1, v1.shape))
print(" v.T: {}        tamaño de v.T: {}".format(v1.T, v1.T.shape))

print("\nUsando un vector de 2 dimensiones:")
print("v:\n", v2)
print("Tamaño de v:", v2.shape)
print("v.T: {}         tamaño de v.T: {}".format(v2.T, v2.T.shape))

Usando un vector de 1 sola dimensión:
   v: [2 4 6]          tamaño de v: (3,)
 v.T: [2 4 6]        tamaño de v.T: (3,)

Usando un vector de 2 dimensiones:
v:
 [[2]
 [4]
 [6]]
Tamaño de v: (3, 1)
v.T: [[2 4 6]]         tamaño de v.T: (1, 3)


### Vector Unitario

In [7]:
# Vector no unitario (se puede usar 1 o 2 dimensiones)
v = np.array([2, 4, 6])
# Vector unitario
v_unit = v/np.linalg.norm(v)

print("Vector unitario:", v_unit)
print("Norma del vector unitario:", np.linalg.norm(v_unit))

Vector unitario: [0.26726124 0.53452248 0.80178373]
Norma del vector unitario: 1.0


## 1.1. Operaciones con Vectores

### Producto Escalar

In [8]:
# Vectores de 1 dimensión:  (3,)
x = np.array([2, 4, 6])
y = np.array([3, 5, 8])

# Producto escalar 
p1 = x.dot(y)
p2 = np.dot(x,y)
print("Producto escalar:", p1)
print("Producto escalar:", p2)

Producto escalar: 74
Producto escalar: 74


In [9]:
# Usando vectores de 2 dimensiones: (3,1)
x = np.array([[2, 4, 6]]).T
y = np.array([[3, 5, 8]]).T

# Producto escalar usando la transpuesta
p3 = np.dot(x.T, y)
print("Producto escalar:", p3)
print("Producto escalar:", p3.item())

# Nota: en este caso, si se usa x.dot(y) habrá un error de dimensión
# x.dot(y)

Producto escalar: [[74]]
Producto escalar: 74


In [10]:
# Ángulo entre 2 vectores
x = np.array([2, 4, 6])
y = np.array([5, 3, 1])

th = np.arccos( np.dot(x,y) / (np.linalg.norm(x)*np.linalg.norm(y)) ) 
print("Ángulo entre los vectores: {:.4f} rad".format(th))
print("Ángulo entre los vectores: {:.2f} deg".format(np.rad2deg(th)))

Ángulo entre los vectores: 0.8861 rad
Ángulo entre los vectores: 50.77 deg


### Norma

In [11]:
x = np.array([2, 4, 6])     # x = np.array([[2, 4, 6]]).T

# Usando el producto punto para la norma Euclideana (solo con vectores de 1 dimensión)
n1 = np.sqrt(np.dot(x,x))
# Usando la función de numpy para la norma Euclideana (con vectores de 1 o 2 dimensiones)
n2 = np.linalg.norm(x)

print("Norma Euclideana (L2):", n1)
print("Norma Euclideana (L2):", n2)

Norma Euclideana (L2): 7.483314773547883
Norma Euclideana (L2): 7.483314773547883


In [12]:
# Norma L1
norma1 = np.linalg.norm(x, 1)
# Norma L-infinito
normaI = np.linalg.norm(x, np.inf)

print("Norma L1:", norma1)
print("Norma L-infinito:", normaI)

Norma L1: 12.0
Norma L-infinito: 6.0


### Producto Vectorial

In [13]:
# Solo aplicable con vectores de 1 dimensión
x = np.array([2, 4, 6])
y = np.array([5, 3, 1])

# Usando la definición (solo vectores de 1 dimensión)
p1 = np.array([x[1]*y[2]-x[2]*y[1], x[2]*y[0]-x[0]*y[2], x[0]*y[1]-x[1]*y[0] ])
# Usando la función de numpy (solo vectores de 1 dimensión)
p2 = np.cross(x, y)

print("Producto vectorial:", p1)
print("Producto vectorial:", p2)

Producto vectorial: [-14  28 -14]
Producto vectorial: [-14  28 -14]


In [14]:
# Verificación de algunas propiedades:
print("x cross x:", np.cross(x, x))
print("x cros y: {}    , y cross x:{}".format(np.cross(x,y), np.cross(y,x)))

x cross x: [0 0 0]
x cros y: [-14  28 -14]    , y cross x:[ 14 -28  14]


### Producto Exterior

In [15]:
# Producto exterior (se usa vectores de 2 dimensiones porque es necesario transponer)
x = np.array([[2, 4, 6]]).T
y = np.array([[5, 3, 1]]).T
# Producto Exterior
pext = np.dot(x, y.T)

print("Producto Exterior:\n", pext)

Producto Exterior:
 [[10  6  2]
 [20 12  4]
 [30 18  6]]


In [16]:
# Producto punto
p1 = np.dot(x.T, y)
# Traza del producto exterior
p2 = np.trace(pext)

print("Producto punto:", p1.item())
print("Traza del producto exterior:", p2)

Producto punto: 28
Traza del producto exterior: 28
