# Tutorial 4: Algebra lineal usando NumPy - Operaciones básicas con Matrices
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/oscar-ramos/fundamentos-robotica-python/blob/main/0-Introduccion/4-algebra-lineal-matrices.ipynb)

Oscar E. Ramos Ponce - Universidad de Ingeniería y Tecnología - UTEC

* Este archivo muestra el uso básico de matrices con NumPy. 
* Las operaciones descritas se basan en el capítulo 2 (matrices) de [este](http://oramosp.epizy.com/teaching/notes/0_algebra_lineal.pdf) documento. La numeración se basa, igualmente, en dicho documento.

In [1]:
import numpy as np

# 2. Matrices

In [2]:
# Definición de una matriz (de 3 x 4)
M = np.array([[1, 4, 7, 9], 
              [4, 1, 5, 2], 
              [6, 3, 0, 1]])

print("Matriz:\n", M)
print("Dimensión de la matriz:", M.shape)

Matriz:
 [[1 4 7 9]
 [4 1 5 2]
 [6 3 0 1]]
Dimensión de la matriz: (3, 4)


In [3]:
# Obtención de una fila o una columna (unidimensional)
print("Fila 0:", M[0,:])
print("Columna 2:", M[:, 2])

Fila 0: [1 4 7 9]
Columna 2: [7 5 0]


In [4]:
# Obtención de una fila o columna (bidimensional, respetando si es fila o columna)
print("Fila 0:\n", M[[0],:])
print("Columna 2:\n", M[:, [2]])

Fila 0:
 [[1 4 7 9]]
Columna 2:
 [[7]
 [5]
 [0]]


### Transpuesta de una matriz

In [5]:
print("Transpuesta:\n", M.T)
print("Dimensión de la transpuesta:", M.T.shape)

Transpuesta:
 [[1 4 6]
 [4 1 3]
 [7 5 0]
 [9 2 1]]
Dimensión de la transpuesta: (4, 3)


In [6]:
# Verificación de las propiedades:
A = np.array([[1, 4, 7], 
              [4, 1, 5]])
B = np.array([[10, 40, 70], 
              [40, 10, 50]])

# Transpuesta de la transpuesta
AT = A.T
ATT = AT.T

print("Matriz A:\n", A)
print("Transpuesta de la transpuesta de A:\n", ATT)

Matriz A:
 [[1 4 7]
 [4 1 5]]
Transpuesta de la transpuesta de A:
 [[1 4 7]
 [4 1 5]]


In [7]:
# Transpuesta de una suma
print("(A + B)^T:\n", (A+B).T)
print("\nA^T + B^T:\n", A.T+B.T)

(A + B)^T:
 [[11 44]
 [44 11]
 [77 55]]

A^T + B^T:
 [[11 44]
 [44 11]
 [77 55]]


In [8]:
# Transpuesta de un producto
A1 = A
B1 = B.T

P1 = (np.dot(A1, B1)).T
P2 = np.dot(B1.T, A1.T)

print("(AB)^T:\n", P1)
print("\nB^T A^T:\n", P2)

(AB)^T:
 [[660 430]
 [430 420]]

B^T A^T:
 [[660 430]
 [430 420]]


## 2.1 Tipos de Matrices

In [9]:
# Matriz triangular superior e inferior
A = np.round( 100*np.random.random((4, 4)), 0)
ATS = np.triu(A)
ATI = np.tril(A)

print("Matriz original:\n", A)
print("\nMatriz triangular superior:\n", ATS)
print("\nMatriz triangular inferior:\n", ATI)

Matriz original:
 [[25. 23. 16. 33.]
 [54. 67. 68.  7.]
 [24. 18. 86.  3.]
 [17. 99. 51. 43.]]

Matriz triangular superior:
 [[25. 23. 16. 33.]
 [ 0. 67. 68.  7.]
 [ 0.  0. 86.  3.]
 [ 0.  0.  0. 43.]]

Matriz triangular inferior:
 [[25.  0.  0.  0.]
 [54. 67.  0.  0.]
 [24. 18. 86.  0.]
 [17. 99. 51. 43.]]


In [10]:
# Matriz diagonal
Adiag = np.diag([1, 5, 8, 2])
print("Matriz diagonal:\n", Adiag)

# Elementos diagonales de una matriz
print("\nElementos diagonales de la matriz:", np.diag(Adiag))

Matriz diagonal:
 [[1 0 0 0]
 [0 5 0 0]
 [0 0 8 0]
 [0 0 0 2]]

Elementos diagonales de la matriz: [1 5 8 2]


In [11]:
# Matriz identidad
I = np.eye(5)
print("Matriz identidad de 5x5:\n", I)

Matriz identidad de 5x5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# Matriz simétrica
A = np.round(100*np.random.random((4, 4)), 0)   # Matriz aleatoria
As = A + A.T       # Matriz simétrica

print("Matriz simétrica:\n", As)

Matriz simétrica:
 [[112.  56.  99. 144.]
 [ 56.  86. 186. 160.]
 [ 99. 186.  80. 143.]
 [144. 160. 143.  26.]]


In [13]:
# Matriz antisimétrica
A = np.round(100*np.random.random((4, 4)), 0)   # Matriz aleatoria
Aa = A - A.T       # Matriz antisimétrica

print("Matriz antisimétrica:\n", Aa)
print("Verificación: -A^T =\n", -Aa.T)

Matriz antisimétrica:
 [[  0.  76.  58.  -9.]
 [-76.   0.  49. -28.]
 [-58. -49.   0. -30.]
 [  9.  28.  30.   0.]]
Verificación: -A^T =
 [[ -0.  76.  58.  -9.]
 [-76.  -0.  49. -28.]
 [-58. -49.  -0. -30.]
 [  9.  28.  30.  -0.]]


In [14]:
# Matriz ortogonal

# La siguiente matriz fue generada usando scipy:
#    from scipy.stats import ortho_group
#    m = ortho_group.rvs(dim=3)

A = np.array([[-0.97435901, -0.0571155 ,  0.21762891],
              [-0.20015248, -0.2218091 , -0.95432683],
              [ 0.10277893, -0.97341591,  0.20468989]])

# Verificación de ortogonalidad
A1 = np.round( np.dot(A, A.T), 3 )
A2 = np.round( np.dot(A.T, A), 3 )
print("A A^T:\n", A1)
print("\nA^T A:\n", A2)

# Verificación de la transpuesta y la inversa
print("\nTranspuesta de A:\n", A.T)
print("\nInversa de A:\n", np.linalg.inv(A))

# Determinante de la matriz simétrica
print("\nDeterminante de A:\n", np.linalg.det(A))

A A^T:
 [[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

A^T A:
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]

Transpuesta de A:
 [[-0.97435901 -0.20015248  0.10277893]
 [-0.0571155  -0.2218091  -0.97341591]
 [ 0.21762891 -0.95432683  0.20468989]]

Inversa de A:
 [[-0.97435901 -0.20015248  0.10277893]
 [-0.0571155  -0.22180911 -0.97341592]
 [ 0.21762891 -0.95432684  0.20468989]]

Determinante de A:
 0.9999999935441564


In [15]:
# Autovalores de una matriz antisimétrica (válido solo si es de 3x3)
L, V = np.linalg.eig(A)

print("Autovalores:\n", L)    # Un autovalor es 1
print("Autovectores:\n", V)   # El autovector con el autovalor 1 es el eje de giro

Autovalores:
 [ 1.        +0.j         -0.99573911+0.09221509j -0.99573911-0.09221509j]
Autovectores:
 [[-0.10350302+0.j         -0.70330901+0.j         -0.70330901-0.j        ]
 [ 0.62272881+0.j         -0.04582221-0.55136625j -0.04582221+0.55136625j]
 [-0.7755617 +0.j          0.05706805-0.44271352j  0.05706805+0.44271352j]]


In [16]:
# Descomposición de una matriz cuadrada en su parte simétrica y asimétrica

A = np.round( 100*np.random.random((3,3)), 0)
As = A + A.T   # Parte simétrica
Aa = A - A.T   # Parte antisimétrica

print("Matriz A:\n", A)
print("\nMatriz simétrica correspondiente:\n", As)
print("\nMatriz antisimétrica correspondiente:\n", Aa)
print("\nMatriz 0.5 Asim + 0.5 Aantisim:\n", 0.5*As + 0.5*Aa)

Matriz A:
 [[49. 60. 52.]
 [40. 31. 64.]
 [85. 85.  5.]]

Matriz simétrica correspondiente:
 [[ 98. 100. 137.]
 [100.  62. 149.]
 [137. 149.  10.]]

Matriz antisimétrica correspondiente:
 [[  0.  20. -33.]
 [-20.   0. -21.]
 [ 33.  21.   0.]]

Matriz 0.5 Asim + 0.5 Aantisim:
 [[49. 60. 52.]
 [40. 31. 64.]
 [85. 85.  5.]]


## 2.2 Multiplicación de matrices

### Producto Matriz Vector

In [17]:
# Matriz bidimensional
A = np.array([[1, 2, 4], 
              [6, 3, 1], 
              [4, 1, 9]])
# Vector unidimensional
x = np.array([1, 5, 2])

# Notar que el resultado tiene 1 sola dimensión (es un vector unidimensional)
P1 = A.dot(x)      # Forma 1
P2 = np.dot(A, x)  # Forma 2

print("Producto Ax (unidimensional):", P1)
print("Producto Ax (unidimensional):", P2)

Producto Ax (unidimensional): [19 23 27]
Producto Ax (unidimensional): [19 23 27]


In [18]:
# Vector bidimensional
x = np.array([[1, 5, 2]]).T

# Al multiplicar, ahora el resultado es un vector columna (bidimensional)
P1 = A.dot(x)      # Forma 1
P2 = np.dot(A, x)  # Forma 2

print("Producto Ax (bidimensional):\n", P1)
print("Producto Ax (bidimensional):\n", P2)

Producto Ax (bidimensional):
 [[19]
 [23]
 [27]]
Producto Ax (bidimensional):
 [[19]
 [23]
 [27]]


In [19]:
# Verificación del producto de filas de la matriz con el vector
P3 = np.array([np.dot(A[0,:], x), 
              np.dot(A[1,:], x),
              np.dot(A[2,:], x)])
print("Producto:\n", P3)

Producto:
 [[19]
 [23]
 [27]]


In [20]:
# Verificación del producto usando suma de columnas
P4 = np.dot(A[:,[0]], x[0,0]) + np.dot(A[:,[1]], x[1,0]) + np.dot(A[:,[2]], x[2,0])
print("Producto:\n", P4)

Producto:
 [[19]
 [23]
 [27]]


### Producto matriz-matriz

In [21]:
A = np.array([[1, 2], 
              [6, 3], 
              [4, 1]])
B = np.array([[10, 20, 40], 
              [60, 30, 10]])

P1 = np.dot(A, B)
P2 = A.dot(B)
P3 = A @ B   # válido a partir de Python 3 (no válido en Python 2)

print("Producto AB:\n", P1)
print("Producto AB:\n", P2)
print("Producto AB:\n", P3)

Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]
Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]
Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]


In [22]:
# Alternativa 1:
P3 = np.array([[np.dot(A[0,:], B[:,0]), np.dot(A[0,:], B[:,1]), np.dot(A[0,:], B[:,2])], 
               [np.dot(A[1,:], B[:,0]), np.dot(A[1,:], B[:,1]), np.dot(A[1,:], B[:,2])], 
               [np.dot(A[2,:], B[:,0]), np.dot(A[2,:], B[:,1]), np.dot(A[2,:], B[:,2])]])
print("Producto AB:\n", P3)

Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]


In [23]:
# Alternativa 2:
P4 = np.dot(A[:,[0]], B[[0],:]) + np.dot(A[:,[1]], B[[1],:])
print("Producto AB:\n", P4)

Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]


In [24]:
# Alternativa 3
P5 = np.hstack(( np.dot(A, B[:,[0]]), np.dot(A, B[:,[1]]), np.dot(A, B[:,[2]]) ))
print("Producto AB:\n", P5)

Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]


In [25]:
# Alternativa 4
P6 = np.vstack(( np.dot(A[[0],:], B), np.dot(A[[1],:], B), np.dot(A[[2],:], B) ))
print("Producto AB:\n", P6)

Producto AB:
 [[130  80  60]
 [240 210 270]
 [100 110 170]]


## 2.3 Matrices Antisimétricas

In [26]:
# Función para generar una matriz antisimétrica de 3x3 a partir de un vector unidimensional de tamaño 3
def skew(v):
    return np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

v1 = np.array([1, 7, 3])
v2 = np.array([6, 2, 8])

# Producto cruz
P1 = np.cross(v1, v2)
P2 = np.dot(skew(v1), v2)

print("Producto cruz v1xv2:", P1)
print("Producto cruz usando matriz antisimétrica:", P2)

Producto cruz v1xv2: [ 50  10 -40]
Producto cruz usando matriz antisimétrica: [ 50  10 -40]


## 2.4 Operaciones con matrices

### Traza de una matriz

In [27]:
A = np.round( 100*np.random.random((3,3)), 0)
B = np.round( 100*np.random.random((3,3)), 0)

# Traza
Tr = np.trace(A)
Tr2 = A[0,0] + A[1,1] + A[2,2]

print("Matriz A:\n", A)
print("Traza de la matriz A:", Tr)
print("Traza de la matriz A:", Tr2)

Matriz A:
 [[40. 43.  7.]
 [70. 17. 40.]
 [12. 60. 61.]]
Traza de la matriz A: 118.0
Traza de la matriz A: 118.0


In [28]:
# Propiedades de la traza: transpuesta
print("Traza de la matriz A:", np.trace(A) )
print("Traza de la matriz A^T:", np.trace(A.T) )

Traza de la matriz A: 118.0
Traza de la matriz A^T: 118.0


In [29]:
S1 = np.trace(A+B)
S2 = np.trace(A)+np.trace(B)
print("Tr(A+B):", S1 )
print("Tr(A)+Tr(B):", S2)

Tr(A+B): 362.0
Tr(A)+Tr(B): 362.0


In [30]:
TAB = np.trace( np.dot(A,B) )
TBA = np.trace( np.dot(B,A) )
print("Tr(AB):", TAB )
print("Tr(BA):", TBA )

Tr(AB): 20264.0
Tr(BA): 20264.0


In [31]:
A = np.round( 10*np.random.random((3,3)), 0)
B = np.round( 10*np.random.random((3,3)), 0)
C = np.round( 10*np.random.random((3,3)), 0)

ABC = A.dot(B).dot(C)
CAB = C.dot(A).dot(B)
BCA = B.dot(C).dot(A)

print("Tr(ABC):", np.trace(ABC))
print("Tr(CAB):", np.trace(CAB))
print("Tr(BCA):", np.trace(BCA))

Tr(ABC): 4858.0
Tr(CAB): 4858.0
Tr(BCA): 4858.0


### Determinante de una matriz

In [32]:
# Matriz
A = 10*np.random.random((3,3))
# Determinante de la matriz
det = np.linalg.det(A)

print("Determinante de A: {:.2f}".format(det))

Determinante de A: 77.78


In [33]:
# Propiedades: determinante de la matriz y de su transpuesta
DA = np.linalg.det(A)
DAT = np.linalg.det(A.T)

print("det(A): {:.3f}".format(DA))
print("det(A^T): {:.3f}".format(DAT))

det(A): 77.781
det(A^T): 77.781


In [34]:
# Propiedades: determinante de un escalar por una matriz
alfa = 3.4
D1 = np.linalg.det(alfa*A)

n = A.shape[0]
D2 = alfa**n*np.linalg.det(A)

print("det(alfa*A): {:.3f}".format(D1))
print("alfa^n*det(A): {:.3f}".format(D2))

det(alfa*A): 3057.113
alfa^n*det(A): 3057.113


In [35]:
# Propiedades: determinante de un producto
A = 10*np.random.random((3,3))
B = 10*np.random.random((3,3))

D1 = np.linalg.det(np.dot(A, B))
D2 = np.dot( np.linalg.det(A), np.linalg.det(B))

print("det(AB): {:.3f}".format(D1))
print("det(A)det(B): {:.3f}".format(D2))

det(AB): 14858.643
det(A)det(B): 14858.643


In [36]:
# Inversa, si la matriz es invertible
A = 10*np.random.random((3,3))

D1 = np.linalg.det( np.linalg.inv(A) )
D2 = 1/np.linalg.det(A)

print("det(A^-1): {:.3f}".format(D1))
print("1/det(A): {:.3f}".format(D2))

det(A^-1): 0.011
1/det(A): 0.011


In [37]:
# Para matrices triangulares o diagonales
Atriang = np.triu(A)

D1 = np.linalg.det(Atriang)
P1 = Atriang[0,0] * Atriang[1,1] * Atriang[2,2]

print("det(A): {:.3f}".format(D1))
print("tr(A): {:.3f}".format(P1))

det(A): 3.524
tr(A): 3.524


### Norma de una matriz

In [38]:
A = 10*np.random.random((4,3))

# Norma de Frobenius
N1 = np.linalg.norm(A)
N2 = np.sqrt(np.trace(np.dot(A.T, A)))
N3 = np.sqrt( np.sum([A[i,j]**2 for i in range(A.shape[0]) for j in range(A.shape[1])]) )

print("Norma de Frobenius de una matriz: {:.4f}".format(N1))
print("Norma de Frobenius de una matriz: {:.4f}".format(N2))
print("Norma de Frobenius de una matriz: {:.4f}".format(N3))

Norma de Frobenius de una matriz: 20.3894
Norma de Frobenius de una matriz: 20.3894
Norma de Frobenius de una matriz: 20.3894


### Inversa de una matriz

In [39]:
# Inversa
A = 10*np.random.random((3,3))
Ainv = np.linalg.inv(A)

print("Matriz A:\n", A)
print("\nInversa de la matriz A:\n", Ainv)

Matriz A:
 [[1.29073994 3.10797232 5.05818285]
 [5.59613712 9.69700712 5.9249397 ]
 [4.42596604 1.0028383  2.43296823]]

Inversa de la matriz A:
 [[-0.13927329  0.01963992  0.24172303]
 [-0.09948626  0.15186861 -0.16300772]
 [ 0.2943678  -0.09832651  0.03847665]]


In [40]:
# Propiedades : inversa y transpuesta
AinvT = np.linalg.inv(A.T)
ATinv = (np.linalg.inv(A)).T

print("(A^T)^-1:\n", AinvT)
print("(A^-1)^T:\n", ATinv)

(A^T)^-1:
 [[-0.13927329 -0.09948626  0.2943678 ]
 [ 0.01963992  0.15186861 -0.09832651]
 [ 0.24172303 -0.16300772  0.03847665]]
(A^-1)^T:
 [[-0.13927329 -0.09948626  0.2943678 ]
 [ 0.01963992  0.15186861 -0.09832651]
 [ 0.24172303 -0.16300772  0.03847665]]


In [41]:
# Inversa de un producto
A = 10*np.random.random((3,3))
B = 10*np.random.random((3,3))

I1 = np.linalg.inv(np.dot(A,B))
I2 = np.dot(np.linalg.inv(B), np.linalg.inv(A))

print("(AB)^-1:\n", I1)
print("(B^-1)(A^-1):\n", I2)

(AB)^-1:
 [[ 0.14619486 -0.13813433  0.01317557]
 [-0.00758239  0.05809323 -0.09170505]
 [-0.0461858   0.00873854  0.07134335]]
(B^-1)(A^-1):
 [[ 0.14619486 -0.13813433  0.01317557]
 [-0.00758239  0.05809323 -0.09170505]
 [-0.0461858   0.00873854  0.07134335]]


## 2.5 Rango de una matriz

In [42]:
A = 10*np.random.random((5,5))

# Rango:
rang = np.linalg.matrix_rank(A)
print("El rango de la matriz es:", rang)

El rango de la matriz es: 5


In [43]:
A = 10*np.random.random((4,7))

# El rango a lo más es el menor número de filas o columnas (4, en este ejemplo)
rang = np.linalg.matrix_rank(A)
print("El rango de la matriz es:", rang)

El rango de la matriz es: 4


In [44]:
# Rango de la matriz transpuesta
rA = np.linalg.matrix_rank(A)
rAT = np.linalg.matrix_rank(A.T)

print("El rango de la matriz A es:", rA)
print("El rango de la matriz A^T es:", rAT)

El rango de la matriz A es: 4
El rango de la matriz A^T es: 4


In [45]:
# Rango de producto
r1 = np.linalg.matrix_rank(A)
r2 = np.linalg.matrix_rank(np.dot(A.T, A))

print("El rango de A es:", r1)
print("El rango de A^T A es:", r2)

El rango de A es: 4
El rango de A^T A es: 4
