# Ejercicios 1: Representaciones Espaciales I (soluciones)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/oscar-ramos/fundamentos-robotica-python/blob/main/3-Representaciones-Espaciales/2-ejercicios-parte1-soluciones.ipynb)

Oscar E. Ramos Ponce, Universidad de Ingeniería y Tecnología - UTEC
Fundamentos de Robótica

Este archivo contiene las soluciones del conjunto de Ejercicios: Representaciones Espaciales (I)

In [1]:
# Se utilizará sympy para el cálculo simbólico
import sympy as sp

# Se utilizará numpy para el cálculo numérico
import numpy as np

### Pregunta 1

In [2]:
# Alias para el seno y coseno simbólicos (de sympy)
cos = sp.cos
sin = sp.sin

# Definición de las matrices de rotación en y, z usando sympy
def sroty(ang):
    Ry = sp.Matrix([[cos(ang), 0, sin(ang)],
                    [0, 1, 0],
                    [-sin(ang), 0, cos(ang)]])
    return Ry

def srotz(ang):
    Rz = sp.Matrix([[cos(ang), -sin(ang), 0],
                   [sin(ang), cos(ang), 0],
                   [0,0,1]])
    return Rz

In [3]:
# Generación de variables simbólicas
t, p = sp.symbols("t p")

# a) Rotación deseada
R = srotz(t)*sroty(p)
#    Para mostrar el resultado en sympy solamente escribir el nombre de la variable (sin print)
R  

Matrix([
[cos(p)*cos(t), -sin(t), sin(p)*cos(t)],
[sin(t)*cos(p),  cos(t), sin(p)*sin(t)],
[      -sin(p),       0,        cos(p)]])

In [4]:
# b) Transpuesta
R.T

Matrix([
[cos(p)*cos(t), sin(t)*cos(p), -sin(p)],
[      -sin(t),        cos(t),       0],
[sin(p)*cos(t), sin(p)*sin(t),  cos(p)]])

### Pregunta 2

In [5]:
# Alias para el seno y coseno numéricos (de NumPy)
cos = np.cos
sin = np.sin
pi = np.pi

def roty(ang):
    Ry = np.array([[cos(ang), 0, sin(ang)],
                   [0, 1, 0],
                   [-sin(ang), 0, cos(ang)]])
    return Ry

def rotz(ang):
    Rz = np.array([[cos(ang), -sin(ang), 0],
                   [sin(ang), cos(ang), 0],
                   [0,0,1]])
    return Rz

def rotx(ang):
    Rx = np.array([[1, 0, 0],
                   [0, cos(ang), -sin(ang)],
                   [0, sin(ang), cos(ang)]])
    return Rx

In [6]:
# Punto en el sistema I
pI = np.array([[1],[1],[1]])

# Matriz de rotación del sistema F con respecto al sistema I
R_IF= roty(pi/2) @ rotz(pi/4)
print(np.round(R_IF, 3))

[[ 0.    -0.     1.   ]
 [ 0.707  0.707  0.   ]
 [-0.707  0.707  0.   ]]


In [7]:
# Punto en el sistema F
pF = R_IF.T @ pI
print(np.round(pF,3))

[[0.   ]
 [1.414]
 [1.   ]]


### Pregunta 3

In [8]:
# Matriz de rotación del sistema A con respecto al sistema B
R_BA = np.array([[1, 0, 0],
                 [0, 0.6, 0.8],
                 [0, -0.8, 0.6]])
# Punto expresado con respecto al sistema B
p_B = np.array([[2, 4, 5]]).T

# Parte a) Punto con respecto al sistema A
p_A = R_BA.T @ p_B
print("Punto en el sistema A:"); print(p_A)

# Parte b) Punto con respecto al sistema B
p_B1 = R_BA @ p_A
print("Punto en el sistema B:"); print(p_B1)

Punto en el sistema A:
[[ 2. ]
 [-1.6]
 [ 6.2]]
Punto en el sistema B:
[[2.]
 [4.]
 [5.]]


### Pregunta 4

In [9]:
RAB = np.array([[1, 0, 0],
                [0, 1/2, -np.sqrt(3)/2],
                [0, np.sqrt(3)/2, 1/2]])
RAC = np.array([[0, 0, -1],
                [0, 1, 0],
                [1, 0, 0]])

# RBC = RBA RAC = RAB^T RAC
RBC = RAB.T @ RAC
RBC

array([[ 0.       ,  0.       , -1.       ],
       [ 0.8660254,  0.5      ,  0.       ],
       [ 0.5      , -0.8660254,  0.       ]])

### Pregunta 5

In [10]:
# Matriz
M = np.array([[0.3536, -0.6124, 0.7071],
              [0.9268, 0.1268, -0.3536],
              [0.1268, 0.7803, 0.6124]])

# Verificación parte 1: el producto de la matriz por su transpuesta es la identidad
print("M^T M:"); print( np.round( M.T @ M, 2) )

# Verificación parte 2: Determinante de la matriz M
print("det(M):"); print(np.linalg.det(M))

M^T M:
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]
det(M):
1.00005332514


Sí es una matriz de rotación

### Pregunta 6

In [11]:
# Parte b) 3 diferentes alternativas de solución (hay más posibles)
R1 = rotz(-pi/2) @ rotx(pi/2)
R2 = rotx(pi/2) @ roty(-pi/2)
R3 = roty(-pi/2) @ rotz(-pi/2)

print("Rz(-pi/2) Rx(pi/2):"); print( np.round(R1) )
print("\nRx(pi/2) Ry(-pi/2):"); print( np.round(R2) )
print("\nRy(-pi/2) Rz(-pi/2):"); print( np.round(R3) )

Rz(-pi/2) Rx(pi/2):
[[ 0.  0. -1.]
 [-1.  0. -0.]
 [ 0.  1.  0.]]

Rx(pi/2) Ry(-pi/2):
[[ 0.  0. -1.]
 [-1.  0. -0.]
 [ 0.  1.  0.]]

Ry(-pi/2) Rz(-pi/2):
[[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0.  1.  0.]]


### Pregunta 7

In [12]:
# Matriz de rotación resultante
R = np.array([ [0, 0.866, -0.5],
               [-1, 0, 0],
               [0, 0.5, 0.866] ])

# Rotación despejada (Rz)
Rz = rotx(-pi/2).T @ R @ roty(pi/2).T
print(np.round(Rz,4))

[[-0.5    0.866 -0.   ]
 [-0.866 -0.5    0.   ]
 [-0.     0.     1.   ]]


In [13]:
# Ángulo obtenido a partir de comparación con la matriz de rotación en z
th = np.arctan2(-0.866, -0.5)
print("\nEl valor de th es:" + str(np.rad2deg(th)))

# Verificación del ángulo obtenido:
print("\nVerificación:"); print(rotz(th))


El valor de th es:-120.00072778082739

Verificación:
[[-0.500011    0.86601905  0.        ]
 [-0.86601905 -0.500011    0.        ]
 [ 0.          0.          1.        ]]


### Pregunta 8

In [14]:
# a) R = Rotx(90)Rotz(30)Roty(50)  ... final respecto de inicial
R = rotx(np.deg2rad(90)) @ rotz(np.deg2rad(30)) @ roty(np.deg2rad(50))
np.round(R,3)

array([[ 0.557, -0.5  ,  0.663],
       [ 0.766,  0.   , -0.643],
       [ 0.321,  0.866,  0.383]])

In [15]:
# b) 
p_i = np.array([3, 5, 1])
p_f = R.T @ p_i
p_f

array([ 5.82162722, -0.6339746 , -0.84067398])