## Representaciones Espaciales - Parte 2
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/oscar-ramos/fundamentos-robotica-python/blob/main/3-Representaciones-Espaciales/2-representaciones-espaciales-II.ipynb)

Oscar E. Ramos Ponce, Universidad de Ingeniería y Tecnología - UTEC
Fundamentos de Robótica

Este archivo contiene algunos ejemplos de las diapositivas del curso

In [1]:
import numpy as np
import sympy as sp

## 1.&nbsp;Transformaciones Homogéneas

### Diap 6: Composición

In [2]:
def Trasl(x,y,z):
    T = np.array([[1, 0, 0, x],
                  [0, 1, 0, y], 
                  [0, 0, 1, z],
                  [0, 0, 0, 1]])
    return T

def Trotx(ang):
    Tx = np.array([[1, 0, 0, 0],
                   [0, np.cos(ang), -np.sin(ang), 0],
                   [0, np.sin(ang),  np.cos(ang), 0],
                   [0, 0, 0, 1]])
    return Tx

T = Trasl(6, -2, 10) @ Trotx(np.pi/2)
np.round(T, 3)

array([[ 1.,  0.,  0.,  6.],
       [ 0.,  0., -1., -2.],
       [ 0.,  1.,  0., 10.],
       [ 0.,  0.,  0.,  1.]])

### Diap 7: Composición

In [3]:
def sTrasl(x,y,z):
    T = sp.Matrix([[1, 0, 0, x],
                   [0, 1, 0, y], 
                   [0, 0, 1, z],
                   [0, 0, 0, 1]])
    return T

def sTrotx(ang):
    Tx = sp.Matrix([[1, 0, 0, 0],
                    [0, sp.cos(ang), -sp.sin(ang), 0],
                    [0, sp.sin(ang),  sp.cos(ang), 0],
                    [0, 0, 0, 1]])
    return Tx

def sTrotz(ang):
    Tz = sp.Matrix([[sp.cos(ang), -sp.sin(ang), 0, 0],
                    [sp.sin(ang),  sp.cos(ang), 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]])
    return Tz

In [4]:
# Variables simbólicas
a, b, d, t = sp.symbols("a b d t")
R = sTrotx(a)*sTrasl(b,0,0)*sTrasl(0,0,d)*sTrotz(t)
R

Matrix([
[       cos(t),       -sin(t),       0,         b],
[sin(t)*cos(a), cos(a)*cos(t), -sin(a), -d*sin(a)],
[sin(a)*sin(t), sin(a)*cos(t),  cos(a),  d*cos(a)],
[            0,             0,       0,         1]])

### Diap 11: Ejemplo 1 

In [5]:
T = np.array([[0, 1, 0, -4],
              [-1, 0, 0, 6],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])
p = np.array([2, 0, 1, 1])

T.dot(p)

array([-4,  4,  1,  1])

### Diap 12: Ejemplo 2

In [6]:
T = Trasl(6, -2, 10) @ Trotx(np.pi/2)
np.round(T, 3)

array([[ 1.,  0.,  0.,  6.],
       [ 0.,  0., -1., -2.],
       [ 0.,  1.,  0., 10.],
       [ 0.,  0.,  0.,  1.]])

In [7]:
p = np.array([-5, 2, -12, 1])

T.dot(p)

array([ 1., 10., 12.,  1.])

### Diap 13: Ejemplo 3

In [8]:
T = Trotx(np.pi/2) @ Trasl(6, -2, 10)
np.round(T, 3)

array([[  1.,   0.,   0.,   6.],
       [  0.,   0.,  -1., -10.],
       [  0.,   1.,   0.,  -2.],
       [  0.,   0.,   0.,   1.]])

In [9]:
p = np.array([-5, 2, -12, 1])

T.dot(p)

array([1., 2., 0., 1.])

### Diap 18: Ejemplo 2

In [10]:
# b)

T01 = np.array([[1,0,0,0], [0,1,0,1], [0,0,1,1], [0,0,0,1]])
T02 = np.array([[1,0,0,-0.5], [0,1,0,1.5], [0,0,1,1], [0,0,0,1]])
T03 = np.array([[0,1,0,-0.5], [1,0,0,1.5], [0,0,-1,3], [0,0,0,1]])

T32 = np.linalg.inv(T03) @ T02
T32

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2.],
       [ 0.,  0.,  0.,  1.]])

## 2.1.&nbsp;Ángulos de Euler ZYZ

### Diap 23: Matriz de rotación equivalente

In [11]:
# Definiciones de las matrices de rotación en y, z usando sympy
def sroty(ang):
    Ry = sp.Matrix([[sp.cos(ang), 0, sp.sin(ang)],
                    [0, 1, 0],
                    [-sp.sin(ang), 0, sp.cos(ang)]])
    return Ry

def srotz(ang):
    Rz = sp.Matrix([[sp.cos(ang), -sp.sin(ang), 0],
                   [sp.sin(ang), sp.cos(ang), 0],
                   [0,0,1]])
    return Rz

def srotx(ang):
    Rx = sp.Matrix([[1, 0, 0],
                    [0, sp.cos(ang), -sp.sin(ang)],
                    [0, sp.sin(ang), sp.cos(ang)]])
    return Rx

In [12]:
# Variables simbólicas
p1, p2, p3 = sp.symbols("p1 p2 p3")

# Matriz de rotación equivalente
R = srotz(p1)*sroty(p2)*srotz(p3)
R

Matrix([
[-sin(p1)*sin(p3) + cos(p1)*cos(p2)*cos(p3), -sin(p1)*cos(p3) - sin(p3)*cos(p1)*cos(p2), sin(p2)*cos(p1)],
[ sin(p1)*cos(p2)*cos(p3) + sin(p3)*cos(p1), -sin(p1)*sin(p3)*cos(p2) + cos(p1)*cos(p3), sin(p1)*sin(p2)],
[                          -sin(p2)*cos(p3),                            sin(p2)*sin(p3),         cos(p2)]])

### Diap 25: Singularidades de Euler ZYZ

In [13]:
# Cuando phi2 = 0:
R = srotz(p1)*sroty(0)*srotz(p3)
R

Matrix([
[-sin(p1)*sin(p3) + cos(p1)*cos(p3), -sin(p1)*cos(p3) - sin(p3)*cos(p1), 0],
[ sin(p1)*cos(p3) + sin(p3)*cos(p1), -sin(p1)*sin(p3) + cos(p1)*cos(p3), 0],
[                                 0,                                  0, 1]])

In [14]:
sp.simplify(R)

Matrix([
[cos(p1 + p3), -sin(p1 + p3), 0],
[sin(p1 + p3),  cos(p1 + p3), 0],
[           0,             0, 1]])

In [15]:
# Cuando phi2: 180
R = srotz(p1)*sroty(sp.pi)*srotz(p3)

sp.simplify(R)

Matrix([
[-cos(p1 - p3), -sin(p1 - p3),  0],
[-sin(p1 - p3),  cos(p1 - p3),  0],
[            0,             0, -1]])

### Diap 26: Ejemplo

In [16]:
# Definiciones de las matrices de rotación en y, z usando numpy
def rotx(ang):
    Rx = np.array([[1, 0, 0],
                   [0, np.cos(ang), -np.sin(ang)],
                   [0, np.sin(ang),  np.cos(ang)]])
    return Rx

def roty(ang):
    Ry = np.array([[np.cos(ang), 0, np.sin(ang)],
                   [0, 1, 0],
                   [-np.sin(ang), 0, np.cos(ang)]])
    return Ry

def rotz(ang):
    Rz = np.array([[np.cos(ang), -np.sin(ang), 0],
                   [np.sin(ang), np.cos(ang), 0],
                   [0,0,1]])
    return Rz

In [17]:
# a) 
R = rotz(np.deg2rad(30)) @ roty(np.deg2rad(50)) @ rotz(np.deg2rad(90))
np.round(R, 3)

array([[-0.5  , -0.557,  0.663],
       [ 0.866, -0.321,  0.383],
       [-0.   ,  0.766,  0.643]])

In [18]:
# b) 
R = rotz(np.deg2rad(-150)) @ roty(np.deg2rad(-50)) @ rotz(np.deg2rad(-90))
np.round(R, 3)

array([[-0.5  , -0.557,  0.663],
       [ 0.866, -0.321,  0.383],
       [ 0.   ,  0.766,  0.643]])

In [19]:
# c) 
# Primera solución (con + en la raíz cuadrada de phi2)
r11 = R[0,0]; r12 = R[0,1]; r13 = R[0,2]
r21 = R[1,0]; r22 = R[1,1]; r23 = R[1,2]
r31 = R[2,0]; r32 = R[2,1]; r33 = R[2,2]

phi2 = np.arctan2(np.sqrt(r13**2+r23**2), r33)
s2 = np.sin(phi2)
phi1 = np.arctan2(r23/s2, r13/s2)
phi3 = np.arctan2(r32/s2, -r31/s2)

angulos = np.array([phi1, phi2, phi3])
print("ZYZ en radianes:", np.round(angulos,3))
print("ZYZ en grados:", np.rad2deg(angulos))

ZYZ en radianes: [0.524 0.873 1.571]
ZYZ en grados: [30. 50. 90.]


In [20]:
# Segunda solución (con - en la raíz cuadrada de phi2)
phi2 = np.arctan2(-np.sqrt(r13**2+r23**2), r33)
s2 = np.sin(phi2)
phi1 = np.arctan2(r23/s2, r13/s2)
phi3 = np.arctan2(r32/s2, -r31/s2)

angulos = np.array([phi1, phi2, phi3])
print("ZYZ en radianes:", np.round(angulos,3))
print("ZYZ en grados:", np.rad2deg(angulos))

ZYZ en radianes: [-2.618 -0.873 -1.571]
ZYZ en grados: [-150.  -50.  -90.]


## 2.2.&nbsp;Ángulos Roll, Pitch, Yaw

### Diap 28: Matriz de rotación equivalente

In [21]:
# Variables simbólicas
r, p, y = sp.symbols("r p y")

# Matriz de rotación equivalente
R = srotz(r)*sroty(p)*srotx(y)
R

Matrix([
[cos(p)*cos(r), sin(p)*sin(y)*cos(r) - sin(r)*cos(y), sin(p)*cos(r)*cos(y) + sin(r)*sin(y)],
[sin(r)*cos(p), sin(p)*sin(r)*sin(y) + cos(r)*cos(y), sin(p)*sin(r)*cos(y) - sin(y)*cos(r)],
[      -sin(p),                        sin(y)*cos(p),                        cos(p)*cos(y)]])

### Diap 30: Singularidades de RPY

In [22]:
# Cuando pitch = 90
R = srotz(r)*sroty(sp.pi/2)*srotx(y)

sp.simplify(R)

Matrix([
[ 0, -sin(r - y), cos(r - y)],
[ 0,  cos(r - y), sin(r - y)],
[-1,           0,          0]])

In [23]:
# Cuando pitch = -90
R = srotz(r)*sroty(-sp.pi/2)*srotx(y)

sp.simplify(R)

Matrix([
[0, -sin(r + y), -cos(r + y)],
[0,  cos(r + y), -sin(r + y)],
[1,           0,           0]])

### Diap 31: Ejemplo RPY

In [24]:
R = np.array([[-0.5, -0.557, 0.663], [0.866, -0.321, 0.383], [0, 0.766, 0.643]])
R

array([[-0.5  , -0.557,  0.663],
       [ 0.866, -0.321,  0.383],
       [ 0.   ,  0.766,  0.643]])

In [25]:
# Primera solución (con + en la raíz cuadrada de pitch)
r11 = R[0,0]; r12 = R[0,1]; r13 = R[0,2]
r21 = R[1,0]; r22 = R[1,1]; r23 = R[1,2]
r31 = R[2,0]; r32 = R[2,1]; r33 = R[2,2]

p = np.arctan2(-r31, np.sqrt(r32**2+r33**2))
cp = np.cos(p)
r = np.arctan2(r21/cp, r11/cp)
y = np.arctan2(r32/cp, r33/cp)

angulos = np.array([r, p, y])
print("RPY en radianes:", np.round(angulos,3))
print("RPY en grados:", np.rad2deg(angulos))

RPY en radianes: [ 2.094 -0.     0.872]
RPY en grados: [120.00072778  -0.          49.98904228]


In [26]:
# Segunda solución (con - en la raíz cuadrada de pitch)

p = np.arctan2(-r31, -np.sqrt(r32**2+r33**2))
cp = np.cos(p)
r = np.arctan2(r21/cp, r11/cp)
y = np.arctan2(r32/cp, r33/cp)

angulos = np.array([r, p, y])
print("RPY en radianes:", np.round(angulos,3))
print("RPY en grados:", np.rad2deg(angulos))

RPY en radianes: [-1.047 -3.142 -2.269]
RPY en grados: [ -59.99927222 -180.         -130.01095772]


## 2.3.&nbsp;Eje/Ángulo

### Diap 35: Fórmula de Rodrigues (forma exponencial)

In [27]:
t, x, y, z = sp.symbols("t x y z")

# Por facilidad se llamará (x,y,z) a los elementos del vector u
uhat = sp.Matrix([[   0, -z,  y],
                  [  z,   0, -x],
                  [ -y,  x,   0]])
uhat                  

Matrix([
[ 0, -z,  y],
[ z,  0, -x],
[-y,  x,  0]])

In [28]:
R = sp.eye(3) + uhat*sp.sin(t) + uhat*uhat*(1-sp.cos(t))

# Forma explícita de la fórmula
R

Matrix([
[(1 - cos(t))*(-y**2 - z**2) + 1,     x*y*(1 - cos(t)) - z*sin(t),     x*z*(1 - cos(t)) + y*sin(t)],
[    x*y*(1 - cos(t)) + z*sin(t), (1 - cos(t))*(-x**2 - z**2) + 1,    -x*sin(t) + y*z*(1 - cos(t))],
[    x*z*(1 - cos(t)) - y*sin(t),     x*sin(t) + y*z*(1 - cos(t)), (1 - cos(t))*(-x**2 - y**2) + 1]])

### Diap 37: Singularidades

In [29]:
# Cuando el ángulo es 0
t = 0
R = sp.eye(3) + uhat*sp.sin(t) + uhat*uhat*(1-sp.cos(t))
R

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [30]:
# Cuando el ángulo es 180°
t = sp.pi
R = sp.eye(3) + uhat*sp.sin(t) + uhat*uhat*(1-sp.cos(t))
R

Matrix([
[-2*y**2 - 2*z**2 + 1,                2*x*y,                2*x*z],
[               2*x*y, -2*x**2 - 2*z**2 + 1,                2*y*z],
[               2*x*z,                2*y*z, -2*x**2 - 2*y**2 + 1]])

### Diap 39: Ejemplo 1

In [31]:
R = np.array([[0.926, -0.304, 0.226], [0.363, 0.881, -0.304], [-0.107, 0.363, 0.926]])
R

array([[ 0.926, -0.304,  0.226],
       [ 0.363,  0.881, -0.304],
       [-0.107,  0.363,  0.926]])

In [32]:
r11 = R[0,0]; r12 = R[0,1]; r13 = R[0,2]
r21 = R[1,0]; r22 = R[1,1]; r23 = R[1,2]
r31 = R[2,0]; r32 = R[2,1]; r33 = R[2,2]

# Usando la raíz positiva
th = np.arctan2(np.sqrt((r21-r12)**2+(r31-r13)**2+(r32-r23)**2)/2, (np.trace(R)-1)/2)
u = 1/(2*np.sin(th)) * np.array([r32-r23, r13-r31, r21-r12])

print("Ángulo:", np.rad2deg(th))
print("Eje:", u)

Ángulo: 29.994679139602383
Eje: [0.66710731 0.33305357 0.66710731]


In [33]:
# Usando la raíz negativa
th = np.arctan2(-np.sqrt((r21-r12)**2+(r31-r13)**2+(r32-r23)**2)/2, (np.trace(R)-1)/2)
u = 1/(2*np.sin(th)) * np.array([r32-r23, r13-r31, r21-r12])

print("Ángulo:", np.rad2deg(th))
print("Eje:", u)

Ángulo: -29.994679139602383
Eje: [-0.66710731 -0.33305357 -0.66710731]


### Diap 40 y 41: Ejemplos 2 y 3

In [34]:
# Ejemplo 2

t = sp.symbols("t")

uhat = sp.Matrix([[  0, 0,  0],
                  [  0, 0, -1],
                  [  0, 1,  0]])
R = sp.eye(3) + uhat*sp.sin(t) + uhat*uhat*(1-sp.cos(t))
R

Matrix([
[1,      0,       0],
[0, cos(t), -sin(t)],
[0, sin(t),  cos(t)]])

In [35]:
# Ejemplo 3
u = np.array([2, 1, 2])
u = u/np.linalg.norm(u)
u

array([0.66666667, 0.33333333, 0.66666667])

In [36]:
t = np.deg2rad(30)
uhat = np.array([[     0, -u[2],  u[1]],
                 [  u[2],     0, -u[0]],
                 [ -u[1],  u[0],    0]])
R = np.eye(3) + uhat*np.sin(t) + uhat@uhat*(1-np.cos(t))

np.round(R,3)

array([[ 0.926, -0.304,  0.226],
       [ 0.363,  0.881, -0.304],
       [-0.107,  0.363,  0.926]])

In [37]:
# Verificación:
print("Determinante:", np.linalg.det(R))
print("R*R^T:\n", np.round(R@R.T, 3))

Determinante: 1.0
R*R^T:
 [[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]


## 2.4.&nbsp;Cuaterniones

### Diap 43: Producto de cuaterniones

In [38]:
x1, y1, z1, w1 = sp.symbols("x1 y1 z1 w1")
x2, y2, z2, w2 = sp.symbols("x2 y2 z2 w2")

# Parte vectorial del cuaterión 1
e1 = sp.Matrix([x1, y1, z1])
# Parte vectorial del cuaterión 2
e2 = sp.Matrix([x2, y2, z2])

In [39]:
# Parte escalar del producto (se requiere el [0] ya que el resultad por defecto es un vector de 1 solo elemento, y se desea dicho elemento)
w12 = w1*w2 - (e1.T *e2)[0]
# Parte vectorial del producto
e12 = w1*e2 + w2*e1 + e1.cross(e2)

print("Parte escalar", w12)
print("Parte vectorial:"); e12

Parte escalar w1*w2 - x1*x2 - y1*y2 - z1*z2
Parte vectorial:


Matrix([
[w1*x2 + w2*x1 + y1*z2 - y2*z1],
[w1*y2 + w2*y1 - x1*z2 + x2*z1],
[w1*z2 + w2*z1 + x1*y2 - x2*y1]])

In [40]:
# Usando la matriz equivalente para el primer cuaternión
Q1hat = sp.Matrix([[ w1, -x1, -y1, -z1],
                   [ x1,  w1, -z1,  y1],
                   [ y1,  z1,  w1, -x1],
                   [ z1, -y1,  x1,  w1]])

# Segundo cuaternión 
Q2 = sp.Matrix([w2, x2, y2, z2])

# Cuaternión producto de Q1 y Q2
Q1hat * Q2

Matrix([
[w1*w2 - x1*x2 - y1*y2 - z1*z2],
[w1*x2 + w2*x1 + y1*z2 - y2*z1],
[w1*y2 + w2*y1 - x1*z2 + x2*z1],
[w1*z2 + w2*z1 + x1*y2 - x2*y1]])

### Diap 48: Ejemplo

In [41]:
R = np.array([[ 0.321, -0.117,  0.940],
              [ 0.683,  0.716, -0.145],
              [-0.656,  0.688,  0.310]])
R

array([[ 0.321, -0.117,  0.94 ],
       [ 0.683,  0.716, -0.145],
       [-0.656,  0.688,  0.31 ]])

In [42]:
r11 = R[0,0]; r12 = R[0,1]; r13 = R[0,2]
r21 = R[1,0]; r22 = R[1,1]; r23 = R[1,2]
r31 = R[2,0]; r32 = R[2,1]; r33 = R[2,2]

w = 0.5 * np.sqrt(1+r11+r22+r33)
ex = 1/(4*w)*(r32-r23)
ey = 1/(4*w)*(r13-r31)
ez = 1/(4*w)*(r21-r12)

Q = [w, ex, ey, ez]
np.round(Q,3)

array([0.766, 0.272, 0.521, 0.261])

In [43]:
# Matriz de rotación equivalente
R = np.array([[2*(w**2+ex**2)-1,   2*(ex*ey-w*ez),   2*(ex*ez+w*ey)],
              [  2*(ex*ey+w*ez), 2*(w**2+ey**2)-1,   2*(ey*ez-w*ex)],
              [  2*(ex*ez-w*ey),   2*(ey*ez+w*ex), 2*(w**2+ez**2)-1]])

np.round(R, 3)

array([[ 0.321, -0.117,  0.94 ],
       [ 0.683,  0.716, -0.144],
       [-0.656,  0.689,  0.31 ]])

## 3.&nbsp;Rotación de Vectores usando Parametrizaciones

### Diap 51: Ejemplo usando eje/águlo

In [44]:
# a) 
v = np.array([3,1,1])
u = np.array([2,1,2])
ang = np.deg2rad(30)

u = u/np.linalg.norm(u)
vf = v*np.cos(ang) + np.cross(u,v)*np.sin(ang) + u*np.dot(u,v)*(1-np.cos(ang))

np.round(vf, 3)

array([2.699, 1.667, 0.967])

In [45]:
# b)
uhat = np.array([[     0, -u[2],  u[1]],
                 [  u[2],     0, -u[0]],
                 [ -u[1],  u[0],    0]])
R = np.eye(3) + uhat*np.sin(ang) + uhat@uhat*(1-np.cos(ang))
np.round(R,3)

array([[ 0.926, -0.304,  0.226],
       [ 0.363,  0.881, -0.304],
       [-0.107,  0.363,  0.926]])

In [46]:
np.round(R @ v, 3)

array([2.699, 1.667, 0.967])

### Diap 54: Ejemplo usando cuaterniones

In [47]:
p = np.array([3, 5, 2])
ang = np.deg2rad(60)
u = np.array([2, 0, 0])

# Eje de giro unitario
u = u/np.linalg.norm(u)

In [48]:
# a)
# Cuaternión asociado con el vector v:
vhat = np.hstack((0,p))
# Cuaternión que representa la rotación
Q = np.array([np.cos(ang/2), u[0]*np.sin(ang/2), u[1]*np.sin(ang/2), u[2]*np.sin(ang/2)])

print(vhat)
print(Q)

[0 3 5 2]
[0.8660254 0.5       0.        0.       ]


In [49]:
# Conjugada del cuaternión que representa la rotación
Qconj = np.array([Q[0], -Q[1], -Q[2], -Q[3]])

In [50]:
# Función que realiza la multiplicación de cuaterniones
def mult_quat(Q1, Q2):
    w1=Q1[0]; x1=Q1[1]; y1=Q1[2]; z1=Q1[3]
    Q1hat = np.array([[ w1, -x1, -y1, -z1],
                      [ x1,  w1, -z1,  y1],
                      [ y1,  z1,  w1, -x1],
                      [ z1, -y1,  x1,  w1]])
    return Q1hat @ Q2

In [51]:
vrot = mult_quat( mult_quat(Q, vhat), Qconj)
np.round(vrot, 3)

array([0.   , 3.   , 0.768, 5.33 ])

In [52]:
# b) Usando una matriz de rotación
vrot = rotx(ang) @ p
np.round(vrot, 3)

array([3.   , 0.768, 5.33 ])